Include information about CVE patches in CycloneDX output
tiiuae/sbomnix pull request #102
Opened 2023-12-23 14:20 UTC by raboof

2023-12-26 06:29 UTC, henrirosten commented
@raboof : thanks for the PR. 
Let me know if/when you want a review on this change.

2023-12-26 12:17 UTC, raboof commented
> @raboof : thanks for the PR. Let me know if/when you want a review on this change.

I think it's ready for a review now.

I didn't add any explicit test, but I did check that the existing test that generates an SBOM for `hello` also contains dependencies that have security patches, and that test still succeeds (indicating the generated sections conform to the schema).

2023-12-26 13:09 UTC, henrirosten requested changes
Thanks for this PR, see the below comments.
Also, can you add a short description to this PR explaining why this change is needed?

2023-12-26 13:09 UTC, henrirosten commented on src/sbomnix/sbomdb.py
> +            m = re.search(r"CVE-\d{4}-\d+", p)
Unless there's a good reason not to, I would ignre the case in this match in case the data is dirty.

2023-12-26 15:07 UTC, raboof commented on src/sbomnix/sbomdb.py
> +            print(p)
oops :heavy_check_mark:

2023-12-27 06:25 UTC, henrirosten approved these changes

2023-12-27 06:26 UTC, merged

2023-12-27 06:26 UTC, henrirosten commented
Thanks, merged.